[0m13:21:10.008361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101aac050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fc22d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fc1e50>]}


============================== 13:21:10.011481 | 1b5de137-e97d-424f-a6c2-e8d4f6915380 ==============================
[0m13:21:10.011481 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:21:10.011800 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/peaceast/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init lightdash-dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:21:24.303180 [info ] [MainThread]: A project called seismotracker already exists here.
[0m13:21:24.308432 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 14.327973, "process_in_blocks": "0", "process_kernel_time": 0.164776, "process_mem_max_rss": "102187008", "process_out_blocks": "0", "process_user_time": 0.432046}
[0m13:21:24.309491 [debug] [MainThread]: Command `dbt init` succeeded at 13:21:24.309314 after 14.33 seconds
[0m13:21:24.310190 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b90bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fc1d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fc39e0>]}
[0m13:21:24.310769 [debug] [MainThread]: Flushing usage events
[0m13:21:24.328229 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:21:47.430672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10433e060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10480e3f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10480df40>]}


============================== 13:21:47.433238 | b4c24263-7093-47da-8e0f-45af4492d780 ==============================
[0m13:21:47.433238 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:21:47.433494 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/peaceast/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init lightdash-dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:21:53.926377 [debug] [MainThread]: Starter project path: /Volumes/EXT/opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m13:21:53.940122 [info ] [MainThread]: 
Your new dbt project "lightdash_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:21:53.941166 [info ] [MainThread]: Setting up your profile.
[0m13:22:19.932802 [info ] [MainThread]: Profile lightdash_dbt written to /Users/peaceast/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:22:19.942944 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 32.534603, "process_in_blocks": "0", "process_kernel_time": 0.168999, "process_mem_max_rss": "103235584", "process_out_blocks": "0", "process_user_time": 0.462837}
[0m13:22:19.944379 [debug] [MainThread]: Command `dbt init` succeeded at 13:22:19.944128 after 32.54 seconds
[0m13:22:19.945359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10480e630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100f24830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104587e30>]}
[0m13:22:19.945974 [debug] [MainThread]: Flushing usage events
[0m13:22:19.963756 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:11:04.051968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056bf440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10553c9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e9a2d0>]}


============================== 20:11:04.055174 | 032122ff-0e7f-4957-9586-b47923c18a93 ==============================
[0m20:11:04.055174 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:11:04.055481 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/peaceast/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m20:11:04.055732 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Volumes/EXT/src/seismotracker/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:11:04.057270 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.037733708, "process_in_blocks": "0", "process_kernel_time": 0.195426, "process_mem_max_rss": "101613568", "process_out_blocks": "0", "process_user_time": 0.544029}
[0m20:11:04.057590 [debug] [MainThread]: Command `dbt run` failed at 20:11:04.057544 after 0.04 seconds
[0m20:11:04.057778 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f659d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10593c8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e9a960>]}
[0m20:11:04.057945 [debug] [MainThread]: Flushing usage events
[0m20:11:04.066094 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:29:36.766735 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107dc4dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f5aa50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f5b850>]}


============================== 20:29:36.769695 | e4b60c83-c668-495b-b744-61d584ec4f99 ==============================
[0m20:29:36.769695 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:29:36.769985 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/peaceast/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:29:36.770298 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Volumes/EXT/colima/default/project/seismotracker/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:29:36.771602 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04075196, "process_in_blocks": "0", "process_kernel_time": 0.138614, "process_mem_max_rss": "100696064", "process_out_blocks": "0", "process_user_time": 0.577171}
[0m20:29:36.771863 [debug] [MainThread]: Command `dbt run` failed at 20:29:36.771813 after 0.04 seconds
[0m20:29:36.772063 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f6b8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100b07f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100a49e50>]}
[0m20:29:36.772260 [debug] [MainThread]: Flushing usage events
[0m20:29:36.779215 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:49:28.451785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104464890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044fb310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044fbf90>]}


============================== 21:49:28.454397 | 860dd9ed-d1d3-4526-9fea-c4d8e3f1da21 ==============================
[0m21:49:28.454397 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:49:28.454659 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/peaceast/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:49:28.454922 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Volumes/EXT/colima/default/project/seismotracker/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:49:28.455682 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.03266754, "process_in_blocks": "0", "process_kernel_time": 0.113318, "process_mem_max_rss": "101498880", "process_out_blocks": "0", "process_user_time": 0.463795}
[0m21:49:28.455872 [debug] [MainThread]: Command `dbt run` failed at 21:49:28.455838 after 0.03 seconds
[0m21:49:28.456027 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044de510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1003ebf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10032de50>]}
[0m21:49:28.456171 [debug] [MainThread]: Flushing usage events
[0m21:49:28.462047 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:01:58.783796 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eddb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f54090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f73c10>]}


============================== 15:01:58.785879 | 69101d60-b402-4157-b355-0c0d1049b502 ==============================
[0m15:01:58.785879 [info ] [MainThread]: Running with dbt=1.9.2
[0m15:01:58.786129 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/peaceast/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --full-refresh', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:01:58.786386 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Volumes/EXT/colima/default/project/seismotracker/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:01:58.787475 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.032781042, "process_in_blocks": "0", "process_kernel_time": 0.116789, "process_mem_max_rss": "101351424", "process_out_blocks": "0", "process_user_time": 0.451458}
[0m15:01:58.787694 [debug] [MainThread]: Command `dbt seed` failed at 15:01:58.787655 after 0.03 seconds
[0m15:01:58.787866 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106de4c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102e1bf50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f55b10>]}
[0m15:01:58.788020 [debug] [MainThread]: Flushing usage events
[0m15:01:58.794449 [debug] [MainThread]: An error was encountered while trying to flush usage events
